# 1、导入numpy作为np，并查看版本
难度等级：L1
问题：将numpy导入为 np 并打印版本号。
答案：

In [31]:
import numpy as np
print(np.__version__)

1.16.1


# 2、如何创建一维数组？
难度等级：L1
问题：创建从0到9的一维数字数组

期望输出：

# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. 如何创建一个布尔数组？
难度等级：L1

问题：创建一个numpy数组元素值全为True（真）的数组

答案：

In [34]:
np.full([2,2],True)

array([[ True,  True],
       [ True,  True]])

# 4. 如何从一维数组中提取满足指定条件的元素？
难度等级：L1

问题：从 arr 中提取所有的奇数

给定：

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
期望的输出：

# > array([1, 3, 5, 7, 9])

In [36]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[arr%2==1]

array([1, 3, 5, 7, 9])

# 5. 如何用numpy数组中的另一个值替换满足条件的元素项？
难度等级：L1

问题：将arr中的所有奇数替换为-1。

给定：

In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
aa = np.where(arr%2==1,arr,-1)
print(aa)
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]
[0 1 2 3 4 5 6 7 8 9]


# 6. 如何在不影响原始数组的情况下替换满足条件的元素项？
难度等级：L2

问题：将arr中的所有奇数替换为-1，而不改变arr。

给定：arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
期望的输出：

out
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
# >  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2==0,-1,arr)
print(out)
arr

[-1  1 -1  3 -1  5 -1  7 -1  9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. 如何改变数组的形状？
难度等级：L1

问题：将一维数组转换为2行的2维数组

给定：

np.arange(10)

# > array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
期望的输出：

# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])

In [55]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. 如何垂直叠加两个数组？
难度等级：L2

问题：垂直堆叠数组a和数组b

给定：

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
期望的输出：

# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9],
# >        [1, 1, 1, 1, 1],
# >        [1, 1, 1, 1, 1]])

In [64]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1) 
np.concatenate([a, b], axis=0)
np.vstack([a,b])
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. 如何水平叠加两个数组？
难度等级：L2

问题：将数组a和数组b水平堆叠。

给定：

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
期望的输出：

# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [68]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. 如何在无硬编码的情况下生成numpy中的自定义序列？
难度等级：L2

问题：创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a。

给定：

a = np.array([1,2,3])`
期望的输出：

# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [70]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. 如何获取两个numpy数组之间的公共项？
难度等级：L2

问题：获取数组a和数组b之间的公共项。

给定：

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
期望的输出：

## array([2, 4])


In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
np.intersect1d(a,b)

array([2, 4])

# 12. 如何从一个数组中删除存在于另一个数组中的项？
难度等级：L2

问题：从数组a中删除数组b中的所有项。

给定：

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
期望的输出：

## >array([1,2,3,4])

In [72]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9]) 
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. 如何得到两个数组元素匹配的位置？
难度等级：L2

问题：获取a和b元素匹配的位置。

给定：

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
期望的输出：

## > (array([1, 3, 5, 7]),)


In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

# 14. 如何从numpy数组中提取给定范围内的所有数字？
难度等级：L2

问题：获取5到10之间的所有项目。

给定：

a = np.array([2, 6, 1, 9, 10, 3, 27])
期望的输出：

(array([6, 9, 10]),)

In [86]:
a = np.array([2, 6, 1, 9, 10, 3, 27]) 
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

# 15. 如何创建一个python函数来处理scalars并在numpy数组上工作？
难度等级：L2

问题：转换适用于两个标量的函数maxx，以处理两个数组。

给定：

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
# > 5
期望的输出：

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
# > array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [88]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# 16. 如何交换二维numpy数组中的两列？
难度等级：L2

问题：在数组arr中交换列1和2。

给定：

arr = np.arange(9).reshape(3,3)

In [105]:
arr = np.arange(9).reshape(3,3) 
print(arr)
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. 如何交换二维numpy数组中的两行？
难度等级：L2

问题：交换数组arr中的第1和第2行：

给定：

arr = np.arange(9).reshape(3,3)
arr

In [93]:
arr = np.arange(9).reshape(3,3) 
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. 如何反转二维数组的行？
难度等级：L2

问题：反转二维数组arr的行。

给定：

# Input
arr = np.arange(9).reshape(3,3)

In [96]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. 如何反转二维数组的列？
难度等级：L2

问题：反转二维数组arr的列。

给定：

# Input
arr = np.arange(9).reshape(3,3)

In [98]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20. 如何创建包含5到10之间随机浮动的二维数组？
难度等级：L2

问题：创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数。

In [124]:
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.78769877 6.70709054 8.72878979]
 [8.27551989 5.51053001 6.08088795]
 [5.63249628 8.18214514 5.20074178]
 [7.0640839  8.40116809 6.12240593]
 [9.22223952 5.31666643 6.09466208]]
